### ISSUE TITLE
Interesting Base64 encoded text.

### ISSUE THREAD

**Issue by mvrozanti** [avdaredevil/SnakeMadNess#1]
Mind revealing why is it encrypted?

**Comment by avdaredevil** [comment]
It's not encrypted, it's __encoded__ 😄. The reason it is that way is that:
- When I am writing the code, those dependencies are not part of the source
- They get added in dynamically through [AP-Compiler](https://github.com/avdaredevil/AP-Compiler), when my [Automated Git Manager](https://github.com/avdaredevil/GIT-AutoManagementSystem) publishes my code to github.

**Comment by mvrozanti** [comment]
I understand it now, thank you.
